### ISSUE TITLE
Provide also a possibility to connect via user/pass (not just with the token)

### ISSUE THREAD

**Issue by tomas-knap** [odalic/odalic-uv-plugin#1]
Jeste mam jednu poznamku k UV DPU - pouziti toho tokenu je pekne - neni treba zadavat name/pass. Nicmene jeden ze smyslu UV DPU je, ze si vytvorim ulohu typu "jednou za mesic pust toto". Nicmene pak mi ten token cas od casu expiruje. Tedy v tomto pripade to uplne idealni neni a lepsi by bylo zadavat username/pass. Nicmene pak by server autorizoval, vytvoril token a musel bys nejak byt schopen ten token vyziskat.

**Comment by brodecva** [comment]
@tomas-knap As discussed, the Odalic server allows to set token expiration to arbitrarily large number of hours and rely on invalidation when the password is reset.
